### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by olcc** [rexim/qemu-android-x86-runner#1]
Hello,
Would you mind adding comments for explaining all the details of you command line?
Are the scripts still valid today?
Olivier

**Comment by rexim** [comment]
@olcc 
> Would you mind adding comments for explaining all the details of you command line?

Could you please be more specific on what exactly is not clear? Check out the [Quick Start](https://github.com/rexim/qemu-android-x86-runner#quick-start) and look inside of the scripts (they are very small). For more details on the QEMU arguments see [their documentation](https://qemu.weilnetz.de/doc/qemu-doc.html).

> Are the scripts still valid today?

I don't know I haven't tried them for awhile. Have you? If something doesn't work please create a separate issue and we can discuss it there.

**Comment by olcc** [comment]
Questions from me would be: 
- Why do you forward the 9999 udp port?
- How to provide an ADC port for the android-x86 VM?
- Do the scripts need to be run as root? (I did so, with success, but I'd prefer avoiding running a VM as root).

**Comment by rexim** [comment]
@olcc good questions! Thank you!

> Why do you forward the 9999 udp port?

You can remove the forwarding. I wrote those scripts when I was working on a project that needed Android x86 and I decided to publish them cause I thought they could be useful for somebody else. The forwarding is just leftovers from the project. I will remove them a little bit later.

> How to provide an ADC port for the android-x86 VM?

I have no idea, sorry! I guess this is something that has to be done via QEMU itself.

> Do the scripts need to be run as root?

I don't remember. I'll check it a little bit later and update the README accordingly.

**Comment by olcc** [comment]
Your scripts were useful to me, because I could run the android VM without spending to much time on learning how `qemu` works.
According to https://www.android-x86.org/documentation/debug.html, an ADC port can be provided with a parameter like `kvm -net user,hostfwd=tcp::4444-:5555`, but I had no success:
```
$ adb connect localhost:4444
$ adb devices
List of devices attached
localhost:4444  offline
```

**Comment by rexim** [comment]
@olcc this is very strange. I have no idea why it doesn't work tho. If you figure out why, feel free to submit a Pull Request to make that knowledge available for everybody.

Thank you for submitting your questions!
